name: custom_player
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  youtube_explode_dart: ^2.3.5




  flutter_hls_parser: ^2.0.1
  media_kit: ^1.1.11
  media_kit_video: ^1.2.5
  media_kit_libs_video: ^1.0.5
dependency_overrides:
  media_kit_native_event_loop:

  media_kit_libs_video:

  media_kit_libs_android_video:
  media_kit_libs_ios_video:
  media_kit_libs_macos_video:
  media_kit_libs_windows_video:
  media_kit_libs_linux:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:


